server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://49.235.198.29:27017/xc_cms
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR